name: Node.js CD - PM2

on:
  push:
    branches: [ 'main' ] # Change this to 'production' if that is your branch name

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync to Project Folder
        # Using rsync ensures we don't get permission errors on the .git folder
        run: |
          rsync -av --exclude='.git' . /home/backend/test/
          cd /home/backend/test/
          npm install

      - name: Restart Application with PM2
        run: |
          cd /home/backend/test/
          # 'reload' provides zero-downtime; if the process is new, it will 'start'
          pm2 reload ttsign --update-env || pm2 start server.js --name ttsign