name: Node.js CD

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Code to Project Folder
        # This moves the new code from the runner folder to your live folder
        run: |
          sudo rsync -va . /home/backend/test/
          cd /home/backend/test/
          sudo npm install

      - name: Restart Server
        run: |
          cd /home/backend/test/
          pm2 restart ttsign || pm2 start server.js --name ttsign