name: Node.js CD

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync to Live Folder
        run: |
          # Copy files from the runner's workspace to your live folder
          cp -r . /home/backend/test/
          cd /home/backend/test/
          # No sudo needed after running chown
          npm install

      - name: Restart PM2
        run: |
          cd /home/backend/test/
          # Restart the app so the new changes show in the browser
          pm2 restart ttsign || pm2 start server.js --name ttsign