name: Deploy to Azure
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into VM and Pull Code (Password Auth)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ 74.225.251.4 }}
          username: ${{ ttSign }}
          password: ${{ Theocenstudios@2580 }}
          script: |
            cd /home/backend/test/
            git pull origin main
            npm install
            pm2 restart ttSign-backend
