name: Node.js CD - Production

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Live Folder
        run: |
          # Use rsync to copy only code files (ignores .git)
          rsync -av --exclude='.git' . /home/backend/test/
          cd /home/backend/test/
          npm install

      - name: Restart PM2
        run: |
          cd /home/backend/test/
          # Reload the specific file to apply changes
          pm2 restart ttsign || pm2 start server.js --name ttsign
          pm2 save