name: Node.js CD

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync to Live Folder
        run: |
          # Moves files while ignoring Git internals to avoid permission errors
          rsync -av --exclude='.git' . /home/backend/test/
          cd /home/backend/test/
          npm install

      - name: Restart PM2
        run: |
          cd /home/backend/test/
          # Force PM2 to reload the files from the disk into memory
          pm2 restart ttsign || pm2 start server.js --name ttsign